class label:
    #ラベルの種類
    LABEL_TYPE = [
        EMPTY, UP_LEFT, UP, UP_RIGHT, LEFT, RIGHT, DOWN_LEFT, DOWN, DOWN_RIGHT,
        UP_LEFT_KNIGHT, UP_RIGHT_KNIGHT, DOWN_LEFT_KNIGHT, DOWN_RIGHT_KNIGHT,
        UP_LEFT_PRO, UP_PRO, UP_RIGHT_PRO, LEFT_PRO, RIGHT_PRO, DOWN_LEFT_PRO, DOWN_PRO, DOWN_RIGHT_PRO,
        UP_LEFT_KNIGHT_PRO, UP_RIGHT_KNIGHT_PRO, DOWN_LEFT_KNIGHT_PRO, DOWN_RIGHT_KNIGHT_PRO,
        DROP_PAWN, DROP_LANCE, DROP_KNIGHT, DROP_SILVER, DROP_GOLD, DROP_BISHOP, DROP_ROOK
        ] = range(32)

    LABEL_TYPE_NUM = len(LABEL_TYPE)